version: 0.2
phases:
  build:
    commands:
      - dotnet test ./src/TrelloClone/TrelloClone.csproj
      - dotnet publish -c release -o ./build-output ./src/TrelloClone/TrelloClone.csproj
      - apt install -y zip
      - zip aws-trello-clone.zip build-output
artifacts:
  files:
    - aws-trello-clone.zip
