version: 0.2
phases:
  build:
    commands:
      - dotnet test ./src/TrelloCloneUnitTests/TrelloCloneUnitTests.csproj
      - dotnet publish -c release -o ./build_output ./src/TrelloClone/TrelloClone.csproj
artifacts:
  files:
    - src/TrelloClone/build_output/*
