version: 0.2
phases:
  build:
    commands:
      - dotnet test ./src/TrelloClone/TrelloClone.csproj
      - dotnet publish -c release -o ./build-output ./src/TrelloClone/TrelloClone.csproj
  post_build:
    commands:
      - dotnet tool install --global dotnet-ef
      - dotnet ef migrations add InitialMigration --project src/TrelloClone/TrelloClone.csproj
      - dotnet ef database update --project src/TrelloClone/TrelloClone.csproj
artifacts:
  files:
    - ./**/*
  base-directory: 'build-output'
  enable-symlinks: yes
